"""empty message

Revision ID: 259567ca018e
Revises: 9a3f6d52a722
Create Date: 2022-01-25 15:30:35.111065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259567ca018e'
down_revision = '9a3f6d52a722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
